### ISSUE TITLE
Device password is reset after daemon restart

### ISSUE THREAD

**Issue by advortsov** [cyanomiko/dcnnt-py#9] opened 2020-12-26 15:33 UTC
I cannot connect the device to the PC because the device password is reset after restarting the daemon.
Always after `dcnnt restart` I see this:
![image](https://user-images.githubusercontent.com/12611411/103154506-b879cd00-47a8-11eb-9c00-beab4cd0dba3.png)

In logs:

> START APP
Starting UDP server...
Starting TCP server...
Incorrect password for device with UIN: 20913467

But I set the same password in Device Connect - Settings (android app), conf.json - self - password (on PC), and in 20913467.device.json

What am I doing wrong?

**Comment by cyanomiko** [comment] 2020-12-26 19:15
Duplicate of #7

**Closed by cyanomiko** 2020-12-26 19:15 UTC
Labels: bug
